# serverless.yml

service: wayru-api

plugins:
  - serverless-offline
  - 'serverless-plugin-typescript-express'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'